StudentTest/StudentTest/Controllers/ResultController.cs
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using System.Web.Routing;
using StudentTest.Models;
using StudentTest.Services;
using StudentTest.ViewModels;
using StudentTest.Converters;
using System.Collections.Generic;

namespace StudentTest.Controllers
{
    public class ResultController : Controller
    {
        private readonly IUserService _userService;
        //private readonly QuestionService _questionService;

        public ResultController()
        {
            _userService = new UserService();
            //_questionService = new QuestionService();
        }

        public ActionResult Index()
        {
            List<UserViewModel> allUsers = _userService.AllUsers();
            return View(allUsers);
        }

        public ActionResult Sessions(int Id)
        {
            List<SessionViewModel> sessions = _userService.OneUser(Id);
            return View(sessions);
        }

        public ActionResult Results(string SessionGuid)
        {
            List<ResultViewModel> result = _userService.UserResults(SessionGuid);
            return View(result);
        }
    }
}

StudentTest/StudentTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Результаты","Index","Result") @*имя ссылки, метод в контроллере, контроллер*@
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.2019 - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>